version: 2
sources:
  - name: journey
    database: "{{ var('journey_database', target.database) }}"
    schema: journey
    tables:
      - name: transaction_data
      - name: product
      - name: hh_demographic
      - name: household
      - name: campaign_desc
      - name: campaign_table
      - name: coupon_redempt
      - name: campaign_household_outcomes
