import { test, expect } from "@playwright/test";

test("author and execute an insurance Recipe against official Cube", async ({ page }, info) => {
  test.skip(process.env.LIVE_INSURANCE !== "1", "Requires official Cube with the insurance model and a writable Recipe store");
  test.setTimeout(120000);
  await page.goto("/recipes/new");
  await page.getByLabel("어떤 분석인가요?").fill("보험금 지급액 변화와 지급 유형별 분석");
  await page.getByLabel("분석할 지표", { exact: true }).selectOption("cube://local/fact_payment/total_payment_amt");
  await page.getByRole("button", { name: "첫 분석 추가" }).click();
  await page.getByRole("button", { name: /시간에 따른 변화/ }).click();
  await page.getByLabel("직전 같은 길이와 비교").check();
  await page.getByRole("button", { name: "분석 단계 추가" }).click();
  await page.getByRole("button", { name: /항목별로 나눠 보기/ }).click();
  await page.getByLabel("나눠 볼 순서", { exact: true }).selectOption("cube://local/fact_payment/payment_type");
  await expect(page.getByLabel("표시할 그룹 수")).not.toBeVisible();
  await page.screenshot({ path: info.outputPath("insurance-recipe.png"), fullPage: true });
  await page.getByRole("button", { name: "초안 저장", exact: true }).click();
  const savedResponse = page.waitForResponse(response => response.request().method() === "PUT" && response.url().includes("/api/recipes/"));
  await page.getByRole("button", { name: "초안 버전 저장" }).click();
  const response = await savedResponse;
  expect(response.status(), await response.text()).toBe(200);
  const recipe = await response.json();
  await expect(page.getByText("v1.0.0 · 초안")).toBeVisible();
  await page.getByRole("button", { name: "발행 검토" }).click();
  await page.getByRole("button", { name: "검증하고 발행" }).click();
  await expect(page.getByLabel("날짜 기준")).toBeVisible();
  await page.getByLabel("날짜 기준").selectOption("cube://local/fact_accident/payment_dt");
  await page.getByLabel("시작일").fill("2026-06-01");
  await page.getByLabel("종료일").fill("2026-06-30");
  await page.getByRole("button", { name: "이 Recipe로 분석" }).click();
  await expect(page).toHaveURL(/\/runs\//, { timeout: 60000 });
  const id = page.url().split("/").pop();
  await expect.poll(async () => (await (await page.request.get(`/api/runs/${id}`)).json()).running, { timeout: 60000 }).toBeNull();
  const run = await (await page.request.get(`/api/runs/${id}`)).json();
  expect(run.status, JSON.stringify(run.steps.map((step: { result: unknown }) => step.result))).toBe("completed");
  expect(run.origin).toBe("web");
  expect(run.recipe_snapshot.name).toBe(recipe.name);
  expect(run.steps).toHaveLength(2);
  expect(run.steps.every((step: { result: { status: string } }) => step.result.status === "success")).toBe(true);
  expect(run.steps[0].result.provenance.queries.length).toBeGreaterThan(0);
  await page.reload();
  await expect(page.getByText("완료", { exact: true }).first()).toBeVisible();
  await expect(page.getByText("대표 그룹", { exact: false })).toBeVisible();
  await expect(page.getByRole("columnheader", { name: "지표 값" })).toBeVisible();
  await expect(page.getByText("전체 결과 보기")).toBeVisible();
  await expect(page.getByText("Eligible groups")).not.toBeVisible();
  await page.screenshot({ path: info.outputPath("insurance-result.png"), fullPage: true });
  await info.attach("saved-run", { body: JSON.stringify({ recipe: recipe.name, run: id }), contentType: "application/json" });
  await page.getByRole("link", { name: "다른 기간으로 실행" }).click();
  await page.getByLabel("날짜 기준").selectOption("cube://local/fact_accident/payment_dt");
  await page.getByLabel("시작일").fill("2026-07-01");
  await page.getByLabel("종료일").fill("2026-07-31");
  await page.getByRole("button", { name: "이 Recipe로 분석" }).click();
  await expect(page).toHaveURL(/\/runs\//);
  await expect(page.getByText("중단", { exact: true }).first()).toBeVisible({ timeout: 60000 });
  await expect(page.getByRole("link", { name: "분석 조건을 바꿔 다시 실행" })).toBeVisible();
});
